name: Build Port
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: dockcross/linux-arm64:latest
    steps:
      - name: Clean and Clone
        run: |
          # Borramos lo que subiste manualmente para no tener conflictos
          rm -rf *
          # Descargamos el código OFICIAL con todas sus piezas internas
          git clone --recursive https://github.com/SuperTux/supertux.git .
          
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          libpng-dev libphysfs-dev libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libvorbis-dev \
          libopenal-dev libcurl4-openssl-dev libfreetype6-dev \
          libogg-dev libboost-all-dev libfmt-dev libglm-dev libraqm-dev
          
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j4
