name: Build Port
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: dockcross/linux-arm64:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          git config --global --add safe.directory /__w/supertux-r36s/supertux-r36s
          git submodule update --init --recursive
          apt-get update && apt-get install -y \
          libpng-dev libphysfs-dev libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libvorbis-dev \
          libopenal-dev libcurl4-openssl-dev libfreetype6-dev \
          libogg-dev libboost-all-dev libfmt-dev libglm-dev libraqm-dev
          
      - name: Build
        run: |
          # Esta línea obliga al compilador a usar solo las librerías de ARM64
          export PKG_CONFIG_PATH=/usr/aarch64-unknown-linux-gnu/lib/pkgconfig
          
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j4
